# Site settings
title: onlywreaths
email: info@onlywreaths.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Christmas wreaths will bring festive cheer to your home. Hang Christmas wreaths and winter garlands to welcome the season of joy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.onlywreaths.co.uk" # the base hostname & protocol for your site
twitter_username: a1craftlimited
github_username:  jekyll

# Build settings
markdown: kramdown
